name: Gaivota
favicon: null
layout_spectrum: 0.10152
typography_spectrum: 0.8813
title: Vilson Gaivota
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2e5ec'
    - '#8b9094'
    - '#a3a8ab'
    - '#5a5f5b'
    - '#181a19'
  brandStrength: 0.6875
  lightness: 0.9375
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
